export const top100Cryptos = {
  BTC: { title: 'Bitcoin', price: 93901.46 },
  ETH: { title: 'Ethereum', price: 1766.78 },
  USDT: { title: 'Tether', price: 0.9998 },
  XRP: { title: 'XRP', price: 2.1 },
  BNB: { title: 'BNB', price: 595.68 },
  SOL: { title: 'Solana', price: 142.58 },
  USDC: { title: 'USD Coin', price: 1.0 },
  DOGE: { title: 'Dogecoin', price: 0.1657 },
  ADA: { title: 'Cardano', price: 0.6488 },
  TRX: { title: 'TRON', price: 0.2441 },
  STETH: { title: 'Lido Staked Ether', price: 1766.29 },
  WBTC: { title: 'Wrapped Bitcoin', price: 93935.0 },
  SUI: { title: 'Sui', price: 3.22 },
  LINK: { title: 'Chainlink', price: 13.31 },
  AVAX: { title: 'Avalanche', price: 19.51 },
  LEO: { title: 'UNUS SED LEO', price: 8.72 },
  XLM: { title: 'Stellar', price: 0.2549 },
  TON: { title: 'Toncoin', price: 3.0 },
  SHIB: { title: 'Shiba Inu', price: 0.0000125 },
  DOT: { title: 'Polkadot', price: 6.25 },
  MATIC: { title: 'Polygon', price: 0.89 },
  LTC: { title: 'Litecoin', price: 84.15 },
  BCH: { title: 'Bitcoin Cash', price: 245.67 },
  DAI: { title: 'Dai', price: 1.0 },
  UNI: { title: 'Uniswap', price: 6.45 },
  WETH: { title: 'Wrapped Ether', price: 1765.5 },
  ICP: { title: 'Internet Computer', price: 7.89 },
  ATOM: { title: 'Cosmos', price: 9.12 },
  XMR: { title: 'Monero', price: 157.34 },
  ETC: { title: 'Ethereum Classic', price: 22.45 },
  OKB: { title: 'OKB', price: 45.67 },
  HBAR: { title: 'Hedera', price: 0.089 },
  FIL: { title: 'Filecoin', price: 5.67 },
  APT: { title: 'Aptos', price: 7.89 },
  CRO: { title: 'Cronos', price: 0.095 },
  VET: { title: 'VeChain', price: 0.025 },
  NEAR: { title: 'NEAR Protocol', price: 5.67 },
  ALGO: { title: 'Algorand', price: 0.25 },
  GRT: { title: 'The Graph', price: 0.15 },
  EOS: { title: 'EOS', price: 1.25 },
  STX: { title: 'Stacks', price: 1.45 },
  FTM: { title: 'Fantom', price: 0.45 },
  AAVE: { title: 'Aave', price: 65.23 },
  XTZ: { title: 'Tezos', price: 0.95 },
  THETA: { title: 'Theta Network', price: 1.12 },
  EGLD: { title: 'Elrond', price: 45.67 },
  BTT: { title: 'BitTorrent', price: 0.0000012 },
  KSM: { title: 'Kusama', price: 35.67 },
  ZEC: { title: 'Zcash', price: 29.45 },
  CHZ: { title: 'Chiliz', price: 0.12 },
  DASH: { title: 'Dash', price: 45.67 },
  ENJ: { title: 'Enjin Coin', price: 0.44 },
  LRC: { title: 'Loopring', price: 0.25 },
  BAT: { title: 'Basic Attention Token', price: 0.25 },
  ONE: { title: 'Harmony', price: 0.02 },
  XEM: { title: 'NEM', price: 0.04 },
  DCR: { title: 'Decred', price: 25.67 },
  ICX: { title: 'ICON', price: 0.25 },
  QTUM: { title: 'Qtum', price: 2.45 },
  SC: { title: 'Siacoin', price: 0.005 },
  ZRX: { title: '0x', price: 0.25 },
  ONT: { title: 'Ontology', price: 0.25 },
  XNO: { title: 'Nano', price: 0.95 },
  WAVES: { title: 'Waves', price: 2.45 },
  LSK: { title: 'Lisk', price: 0.95 },
  BSV: { title: 'Bitcoin SV', price: 45.67 },
  ZEN: { title: 'Horizen', price: 5.67 },
  REP: { title: 'Augur', price: 5.67 },
  DGB: { title: 'DigiByte', price: 0.01 },
  ARDR: { title: 'Ardor', price: 0.12 },
  KMD: { title: 'Komodo', price: 0.25 },
  XVG: { title: 'Verge', price: 0.005 },
  PIVX: { title: 'PIVX', price: 0.25 },
  BCN: { title: 'Bytecoin', price: 0.0002 },
  MONA: { title: 'MonaCoin', price: 1.25 },
  FCT: { title: 'Factom', price: 1.25 },
  GAME: { title: 'GameCredits', price: 0.25 },
  SYS: { title: 'Syscoin', price: 0.12 },
  NXT: { title: 'Nxt', price: 0.01 },
  STEEM: { title: 'Steem', price: 0.25 },
  GLM: { title: 'Golem', price: 0.25 },
  CVC: { title: 'Civic', price: 0.12 },
  ETP: { title: 'Metaverse ETP', price: 0.25 },
  STORJ: { title: 'Storj', price: 0.25 },
  SNT: { title: 'Status', price: 0.02 },
  MAID: { title: 'MaidSafeCoin', price: 0.25 },
  POWR: { title: 'Power Ledger', price: 0.25 },
  DENT: { title: 'Dent', price: 0.0005 },
  PAY: { title: 'TenX', price: 0.25 },
  REQ: { title: 'Request', price: 0.12 },
  AGIX: { title: 'SingularityNET', price: 0.25 },
  FUN: { title: 'FunFair', price: 0.005 },
  CND: { title: 'Cindicator', price: 0.005 },
  NCASH: { title: 'Nucleus Vision', price: 0.005 },
  AMB: { title: 'Ambrosus', price: 0.005 },
  BNT: { title: 'Bancor', price: 0.25 },
  RLC: { title: 'iExec RLC', price: 0.25 },
  KNC: { title: 'Kyber Network', price: 0.25 },
  AST: { title: 'AirSwap', price: 0.12 },
  ICN: { title: 'Iconomi', price: 0.25 },
  MLN: { title: 'Melon', price: 0.25 },
  SNGLS: { title: 'SingularDTV', price: 0.005 },
  GNO: { title: 'Gnosis', price: 0.25 },
  WINGS: { title: 'Wings', price: 0.005 },
  EDG: { title: 'Edgeless', price: 0.005 },
  GUP: { title: 'Matchpool', price: 0.005 },
  BCPT: { title: 'BlockMason Credit Protocol', price: 0.005 },
  SALT: { title: 'Salt', price: 0.25 },
  ENG: { title: 'Enigma', price: 0.25 },
  CFI: { title: 'Cofound.it', price: 0.005 },
  DAT: { title: 'Datum', price: 0.005 },
  MOD: { title: 'Modum', price: 0.25 },
  ADX: { title: 'AdEx', price: 0.25 },
  WABI: { title: 'Wabi', price: 0.25 },
  BAY: { title: 'BitBay', price: 0.005 },
  SUB: { title: 'Substratum', price: 0.005 },
  NAV: { title: 'NavCoin', price: 0.25 },
  LBC: { title: 'LBRY Credits', price: 0.005 },
  CLOAK: { title: 'CloakCoin', price: 0.25 },
  UBQ: { title: 'Ubiq', price: 0.25 },
  PPC: { title: 'Peercoin', price: 0.25 },
  FTC: { title: 'Feathercoin', price: 0.005 },
  VTC: { title: 'Vertcoin', price: 0.25 },
  VIA: { title: 'Viacoin', price: 0.25 },
  GRC: { title: 'GridCoin', price: 0.005 },
  XDN: { title: 'DigitalNote', price: 0.005 },
  EMC: { title: 'Emercoin', price: 0.25 },
  NXS: { title: 'Nexus', price: 0.25 },
  AEON: { title: 'Aeon', price: 0.25 },
  FLO: { title: 'FlorinCoin', price: 0.005 },
  MOON: { title: 'Mooncoin', price: 0.0001 },
  EMC2: { title: 'Einsteinium', price: 0.005 },
  RDD: { title: 'ReddCoin', price: 0.0001 },
  POT: { title: 'PotCoin', price: 0.005 },
  CANN: { title: 'CannabisCoin', price: 0.005 },
  CURE: { title: 'CureCoin', price: 0.005 },
};
