name: Deploy Multiple Site Versions to Pages

on:
  push:
    # TODO: rename to main
    branches: ['v2-embedded-wallet-deployment']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['direct', 'backend-proxy']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          ENV_FILENAME: ${{ matrix.profile == 'backend-proxy' && 'backend-proxy.env' || '' }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.profile }} # Results in 'build-direct' and 'build-backend-proxy'
          path: './dist'
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download 'backend-proxy' build (for root deployment)
        uses: actions/download-artifact@v4
        with:
          name: build-backend-proxy
          path: backend-proxy # Content for the root of the site

      - name: Download 'direct' build (for /ew deployment)
        uses: actions/download-artifact@v4
        with:
          name: build-direct
          path: direct # Content for the /ew subdirectory

      - name: Prepare final deployment structure
        run: |
          echo "Preparing merged content directory..."
          mkdir -p merged-content
          echo "Copying main site content (backend-proxy) to merged-content root..."
          cp -r backend-proxy/* merged-content/
          echo "Creating /ew directory in merged-content..."
          mkdir -p merged-content/ew
          echo "Copying secondary site content (direct) to merged-content/ew..."
          cp -r direct/* merged-content/ew/
          echo "Final structure prepared."
          ls -R merged-content

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload merged artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './merged-content'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
